# Generated by Django 3.1.1 on 2020-12-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hostel',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
