# Generated by Django 3.1.1 on 2020-09-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='donated_pics'),
        ),
    ]
