# Generated by Django 3.1.1 on 2020-09-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
